In [1]:
import os
print(os.getcwd())

d:\proj_ia\lanchonete_bellamaya_project2

In [2]:
from src.database import salvar_cliente, get_cliente

chat_id_teste = "teste_123"
salvar_cliente(chat_id_teste, nome="Silas", telefone="5511999999999")
print(get_cliente(chat_id_teste))

{'chat_id': 'teste_123', 'nome': 'Silas', 'telefone': '5511999999999', 'data_cadastro': '2026-02-25 23:16:28'}

In [3]:
import sys
import os
import pandas as pd
from dotenv import load_dotenv

# Adiciona o diretório atual ao path para importar os módulos de src/
sys.path.append(os.getcwd())

# Carrega variáveis de ambiente (.env)
load_dotenv()

print("✅ Ambiente configurado.")
print(f"Diretório de Trabalho: {os.getcwd()}")
if os.getenv("OPENAI_API_KEY"):
    print("✅ API Key da OpenAI detectada.")
else:
    print("❌ AVISO: API Key da OpenAI não encontrada no .env")

✅ Ambiente configurado.
Diretório de Trabalho: d:\proj_ia\lanchonete_bellamaya_project2
✅ API Key da OpenAI detectada.

In [4]:
from src.database import salvar_cliente, get_cliente

print("🧪 TESTE DO BANCO DE DADOS (CLIENTES)...\n")

chat_id_teste = "teste_123"
nome_teste = "Samuel Teste"
telefone_teste = "11999999999"

# 1) Salvar
print(f"💾 Salvando cliente: {nome_teste}...")
salvar_cliente(chat_id_teste, nome=nome_teste, telefone=telefone_teste)

# 2) Buscar
print(f"🔍 Buscando cliente {chat_id_teste}...")
dados_cliente = get_cliente(chat_id_teste)

print("📦 Retorno do get_cliente:", dados_cliente)
print("🧪 Tipo retornado:", type(dados_cliente))

if dados_cliente:
    nome_recuperado = dados_cliente["nome"]  # get_cliente retorna dict

    if nome_recuperado == nome_teste:
        print(f"✅ SUCESSO! Nome recuperado corretamente: {nome_recuperado}")
    else:
        print(f"⚠️ Nome diferente: Esperado '{nome_teste}', veio '{nome_recuperado}'")
else:
    print("❌ ERRO: Cliente não encontrado no banco.")

🧪 TESTE DO BANCO DE DADOS (CLIENTES)...

💾 Salvando cliente: Samuel Teste...
🔍 Buscando cliente teste_123...
📦 Retorno do get_cliente: {'chat_id': 'teste_123', 'nome': 'Samuel Teste', 'telefone': '11999999999', 'data_cadastro': '2026-02-25 23:16:28'}
🧪 Tipo retornado: <class 'dict'>
✅ SUCESSO! Nome recuperado corretamente: Samuel Teste

In [5]:
from src.knowledge_base import load_menu_tool
from llama_index.core import VectorStoreIndex

# Carrega a ferramenta
menu_tool = load_menu_tool()

if menu_tool:
    print(f"✅ Tool carregada: {menu_tool.metadata.name}")
    print(f"Descrição: {menu_tool.metadata.description}")
else:
    print("❌ Erro ao carregar a Tool do cardápio.")

d:\proj_ia\lanchonete_bellamaya_project2\.venv\lib\site-packages\pydantic\_internal\_generate_schema.py:2249: UnsupportedFieldAttributeWarning: The 'validate_default' attribute with value True was provided to the `Field()` function, which has no effect in the context it was used. 'validate_default' is field-specific metadata, and can only be attached to a model field using `Annotated` metadata or by assignment. This may have happened because an `Annotated` type alias using the `type` statement was used, or if the `Field()` function was attached to a single member of a union type.
  warnings.warn(

✅ Tool carregada: consultar_cardapio
Descrição: Use esta ferramenta para buscar PREÇOS e ITENS no cardápio.

In [6]:
# Importamos a função de busca direta que criamos no knowledge_base.py
from src.knowledge_base import buscar_no_cardapio

print("🧪 INICIANDO TESTE DE BUSCA BLINDADA...\n")

# Teste 1: O item que estava dando problema (Coca Lata)
termo1 = "coca lata"
print(f"🔎 Buscando: '{termo1}'")
resposta_1 = buscar_no_cardapio(termo1)
print(f"Resultado:\n{resposta_1}\n")

print("-" * 30 + "\n")

# Teste 2: Outro item para garantir (BM14)
termo2 = "bm14"
print(f"🔎 Buscando: '{termo2}'")
resposta_2 = buscar_no_cardapio(termo2)
print(f"Resultado:\n{resposta_2}")

🧪 INICIANDO TESTE DE BUSCA BLINDADA...

🔎 Buscando: 'coca lata'
📂 Cardápio encontrado em: d:\proj_ia\lanchonete_bellamaya_project2\data\cardapio.xlsx
Resultado:
Encontrei 1 itens para 'coca lata':

- Código/Nome: coca cola
  Descrição: Refrigerante Lata 350ml
  Preço: R$ 6.00
---


------------------------------

🔎 Buscando: 'bm14'
Resultado:
Encontrei 1 itens para 'bm14':

- Código/Nome: BM14 – Frango Cheddar
  Descrição: Frango grelhado, cheddar cremoso e bacon
  Preço: R$ 36.00
---

In [7]:
from src.order_manager import calcular_total_carrinho, formatar_resumo_pedido, gerar_id_pedido

# Simula itens identificados pelo agente
itens_carrinho = [
    {'item': 'X-Burger', 'preco': 25.00, 'qtd': 2},
    {'item': 'Coca-Cola Lata', 'preco': 6.00, 'qtd': 1}
]

# 1. Teste de Cálculo
total = calcular_total_carrinho(itens_carrinho)
print(f"Total Calculado: R$ {total:.2f}")
assert total == 56.00 # (25*2) + 6

# 2. Teste de Formatação
texto_final = formatar_resumo_pedido(
    itens=itens_carrinho,
    total=total,
    metodo_pagamento="Pix",
    endereco="Rua dos Desenvolvedores, 101",
    nome_cliente="Samuel"
)

print("\n--- RESUMO GERADO ---")
print(texto_final)

Total Calculado: R$ 56.00

--- RESUMO GERADO ---
🧾 *RESUMO DO PEDIDO - BELLA MAYA*
👤 Cliente: Samuel
📅 Data: 09/03/2026 21:46
-------------------------
2x X-Burger
   (R$ 25.00) ➡️ R$ 50.00
1x Coca-Cola Lata
   (R$ 6.00) ➡️ R$ 6.00
-------------------------
💰 *TOTAL FINAL: R$ 56.00*
💳 Pagamento: Pix
📍 Entrega: Rua dos Desenvolvedores, 101
-------------------------

In [8]:
from unittest.mock import MagicMock
import src.agent_engine as agent_engine
from src import waha_client
# <--- CERTO (sem o "src.")

# Substitui a função real de envio por um Mock que apenas imprime na tela
waha_client.send_to_group = MagicMock(side_effect=lambda gid, msg: print(f"\n[MOCK WHATSAPP GRUPO] Enviando para {gid}:\n{msg}"))
waha_client.send_message = MagicMock(side_effect=lambda cid, msg: print(f"\n[MOCK WHATSAPP PRIVADO] Enviando para {cid}:\n{msg}"))

print("✅ Waha Client mockado com sucesso. Mensagens serão printadas aqui.")

✅ Waha Client mockado com sucesso. Mensagens serão printadas aqui.

In [9]:
from src.agent_engine import create_agent

# ID de teste para manter a memória da sessão
chat_id_simulado = "teste_notebook_user_1"

print("🤖 Iniciando Agente Bella Maya...")
agent = create_agent(chat_id_simulado)

# Histórico de conversa simulada
mensagens_usuario = [
    "Olá, gostaria de fazer um pedido.",
    "Meu nome é Samuel.",
    "Qual o preço do X-Burger?",
    "Vou querer 1 X-Burger e 1 Coca-Cola.",
    "Pode fechar a conta.",
    "Moro na Av. Paulista, 1000.",
    "Vou pagar no Pix."
]

print("--- INÍCIO DA SIMULAÇÃO ---\n")

for msg in mensagens_usuario:
    print(f"👤 Usuário: {msg}")

    # O Agente processa
    response = agent.chat(msg)

    print(f"🤖 Agente: {response}\n")
    print("-" * 50)

🤖 Iniciando Agente Bella Maya...

d:\proj_ia\lanchonete_bellamaya_project2\.venv\lib\site-packages\llama_index\agent\openai\base.py:144: DeprecationWarning: Call to deprecated class OpenAIAgent. (OpenAIAgent has been deprecated and is not maintained.

`FunctionAgent` is the recommended replacement.

See the docs for more information on updated agent usage: https://docs.llamaindex.ai/en/stable/understanding/agent/)
  return cls(
d:\proj_ia\lanchonete_bellamaya_project2\.venv\lib\site-packages\deprecated\classic.py:184: DeprecationWarning: Call to deprecated class AgentRunner. (AgentRunner has been deprecated and is not maintained.

This implementation will be removed in a v0.13.0.

See the docs for more information on updated agent usage: https://docs.llamaindex.ai/en/stable/understanding/agent/)
  return old_new1(cls, *args, **kwargs)
d:\proj_ia\lanchonete_bellamaya_project2\.venv\lib\site-packages\llama_index\agent\openai\step.py:213: DeprecationWarning: Call to deprecated class OpenAIAgentWorker. (OpenAIAgentWorker has been deprecated and is not maintained.

`FunctionAgent` is the recommended replacement.

See the docs for more information on updated agent usage: https://docs.llamaindex.ai/en/stable/understanding/agent/)
  return cls(

--- INÍCIO DA SIMULAÇÃO ---

👤 Usuário: Olá, gostaria de fazer um pedido.
Added user message to memory: Olá, gostaria de fazer um pedido.
🤖 Agente: Olá! Seja bem-vindo à *Lanchonete Bella Maya*! 😊 Qual é o seu nome?

--------------------------------------------------
👤 Usuário: Meu nome é Samuel.
Added user message to memory: Meu nome é Samuel.
🤖 Agente: Prazer em conhecê-lo, Samuel! 😊 Você gostaria de ver o nosso cardápio?

--------------------------------------------------
👤 Usuário: Qual o preço do X-Burger?
Added user message to memory: Qual o preço do X-Burger?
=== Calling Function ===
Calling function: consultar_cardapio with args: {"termo_busca":"X-Burger"}
Got output: Encontrei 1 itens para 'x-burger':

- Código/Nome: BM03 – X-Burger
  Descrição: Hambúrguer bovino artesanal com mussarela no pão brioche
  Preço: R$ 26.00
---

========================

🤖 Agente: O *X-Burger* (Hambúrguer bovino artesanal com mussarela no pão brioche) custa *R$ 26,00*. 🍔

Você gostaria de pedir mais alguma coisa?

--------------------------------------------------
👤 Usuário: Vou querer 1 X-Burger e 1 Coca-Cola.
Added user message to memory: Vou querer 1 X-Burger e 1 Coca-Cola.
=== Calling Function ===
Calling function: consultar_cardapio with args: {"termo_busca": "Coca-Cola"}
Got output: Não encontrei nenhum item correspondente a 'coca-cola' no cardápio.
========================

=== Calling Function ===
Calling function: consultar_cardapio with args: {"termo_busca": "Refrigerante"}
Got output: Encontrei 8 itens para 'refrigerante':

- Código/Nome: coca cola
  Descrição: Refrigerante Lata 350ml
  Preço: R$ 6.00
---
- Código/Nome: fanta
  Descrição: Refrigerante Lata 350ml
  Preço: R$ 6.00
---
- Código/Nome: guaraná antartica
  Descrição: Refrigerante Lata 350ml
  Preço: R$ 6.00
---
- Código/Nome: pepsi
  Descrição: Refrigerante Lata 350ml
  Preço: R$ 6.00
---
- Código/Nome: coca cola
  Descrição: Refrigerante garrafa 600ml
  Preço: R$ 8.00
---
- Código/Nome: fanta
  Descrição: Refrigerante garrafa 600ml
  Preço: R$ 8.00
---
- Código/Nome: pepsi
  Descrição: Refrigerante garrafa 600ml
  Preço: R$ 8.00
---
- Código/Nome: coca cola
  Descrição: Refrigerante garrafa 1 litro
  Preço: R$ 10.00
---

========================

🤖 Agente: Aqui está o que você pediu:

- 1x *BM03 - X-Burger* (Hambúrguer bovino artesanal com mussarela no pão brioche) - R$ 26,00
- 1x *Coca-Cola* (Refrigerante Lata 350ml) - R$ 6,00

Agora, vamos calcular o total:

*Total: R$ 26,00 + R$ 6,00 = R$ 32,00* ✅

Você tem alguma observação para a cozinha? (ex: tirar cebola, ponto da carne, enviar maionese)

--------------------------------------------------
👤 Usuário: Pode fechar a conta.
Added user message to memory: Pode fechar a conta.
🤖 Agente: Perfeito, Samuel! 😊 Agora, por favor, me informe o seu endereço completo de entrega e a forma de pagamento.

--------------------------------------------------
👤 Usuário: Moro na Av. Paulista, 1000.
Added user message to memory: Moro na Av. Paulista, 1000.
🤖 Agente: Ótimo, Samuel! E qual será a forma de pagamento? (ex: dinheiro, cartão de crédito, etc.)

--------------------------------------------------
👤 Usuário: Vou pagar no Pix.
Added user message to memory: Vou pagar no Pix.
=== Calling Function ===
Calling function: finalizar_pedido with args: {"nome":"Samuel","itens":"1x BM03 - X-Burger (Hambúrguer bovino artesanal com mussarela no pão brioche), 1x coca cola (Refrigerante Lata 350ml)","observacoes":"Nenhuma","total":32.0,"pagamento":"Pix","endereco":"Av. Paulista, 1000"}
❌ Erro ao enviar mensagem para cozinha via WAHA: HTTPConnectionPool(host='waha', port=3000): Max retries exceeded with url: /api/sendText (Caused by NameResolutionError("HTTPConnection(host='waha', port=3000): Failed to resolve 'waha' ([Errno 11001] getaddrinfo failed)"))
Got output: ✅ *PEDIDO CONFIRMADO* #20260309214702
📅 *Data/Hora:* 09/03/2026 às 21:47
👤 *Cliente:* Samuel
📍 *Endereço:* Av. Paulista, 1000
--------------------------------
🍔 *ITENS DO PEDIDO:*
1x BM03 - X-Burger (Hambúrguer bovino artesanal com mussarela no pão brioche), 1x coca cola (Refrigerante Lata 350ml)
--------------------------------
📝 *OBSERVAÇÕES PARA A COZINHA:*
Nenhuma
--------------------------------
💰 *TOTAL:* R$ 32.00
💳 *Pagamento:* Pix
--------------------------------
🚀 *Status:* Enviado para a cozinha! Aguarde a entrega. 😋

📲 *PAGAMENTO VIA PIX:*
Por favor, acesse o link abaixo para gerar seu código Pix:
👉 https://pagamento.bellamaya.com.br/pix/gerar

⚠️ *IMPORTANTE:* Você pode me enviar o comprovante por aqui ou apresentar para o entregador na hora da entrega! 🏍️
========================

🤖 Agente: ✅ *Pedido Confirmado!* O número do seu pedido é *#20260309214702*.

📅 *Data/Hora:* 09/03/2026 às 21:47
👤 *Cliente:* Samuel
📍 *Endereço:* Av. Paulista, 1000
--------------------------------
🍔 *ITENS DO PEDIDO:*
1x BM03 - X-Burger (Hambúrguer bovino artesanal com mussarela no pão brioche), 1x coca cola (Refrigerante Lata 350ml)
--------------------------------
📝 *OBSERVAÇÕES PARA A COZINHA:*
Nenhuma
--------------------------------
💰 *TOTAL:* R$ 32,00
💳 *Pagamento:* Pix
--------------------------------
🚀 *Status:* Enviado para a cozinha! Aguarde a entrega. 😋

📲 *PAGAMENTO VIA PIX:*
Por favor, acesse o link abaixo para gerar seu código Pix:
👉 https://pagamento.bellamaya.com.br/pix/gerar

⚠️ *IMPORTANTE:* Você pode me enviar o comprovante por aqui ou apresentar para o entregador na hora da entrega! 🏍️

Se precisar de mais alguma coisa, estou à disposição! 🍟🥤

--------------------------------------------------

In [10]:
import pandas as pd
import os

# 1. Define o caminho esperado
caminho_arquivo = os.path.join("data", "cardapio.xlsx")

print(f"🔍 Verificando arquivo em: {os.path.abspath(caminho_arquivo)}\n")

# 2. Verifica se o arquivo existe fisicamente
if not os.path.exists(caminho_arquivo):
    print("❌ ERRO CRÍTICO: O arquivo 'cardapio.xlsx' NÃO foi encontrado na pasta 'data'.")
    print("👉 Verifique se você fez o upload do arquivo ou se ele está com o nome correto.")
else:
    print("✅ Arquivo encontrado! Tentando ler...\n")

    try:
        # 3. Tenta ler o Excel
        df = pd.read_excel(caminho_arquivo)

        # 4. Mostra informações básicas
        print(f"📊 Colunas encontradas: {list(df.columns)}")
        print(f"🔢 Total de linhas: {len(df)}")

        # 5. TESTE DE FOGO: Procura pelo item BM14 (que o bot não achou)
        # Procura em todas as colunas de texto
        termo_busca = "BM14"
        encontrado = df[df.apply(lambda row: row.astype(str).str.contains(termo_busca, case=False).any(), axis=1)]

        if not encontrado.empty:
            print(f"\n✅ SUCESSO: O item '{termo_busca}' ESTÁ na planilha!")
            display(encontrado) # Mostra a linha exata encontrada
        else:
            print(f"\n⚠️ ALERTA: O arquivo existe, mas o item '{termo_busca}' NÃO foi encontrado dentro dele.")
            print("👉 Verifique se o código está escrito corretamente na coluna 'Produto'.")

        print("\n👀 Primeiras 5 linhas do seu cardápio:")
        display(df.head())

    except Exception as e:
        print(f"❌ Erro ao abrir o Excel: {e}")

🔍 Verificando arquivo em: d:\proj_ia\lanchonete_bellamaya_project2\data\cardapio.xlsx

✅ Arquivo encontrado! Tentando ler...

📊 Colunas encontradas: ['Produto', 'Descricao', 'Preco']
🔢 Total de linhas: 53

✅ SUCESSO: O item 'BM14' ESTÁ na planilha!

                  Produto                                 Descricao  Preco
13  BM14 – Frango Cheddar  Frango grelhado, cheddar cremoso e bacon     36

👀 Primeiras 5 linhas do seu cardápio:

,Produto,Descricao,Preco
0,BM01 – Clássico Bella,"Hambúrguer bovino artesanal, alface, tomate, m...",25
1,BM02 – X-Salada,"Hambúrguer bovino, mussarela, alface, tomate e...",26
2,BM03 – X-Burger,Hambúrguer bovino artesanal com mussarela no p...,26
3,BM04 – X-Bacon Tradicional,"Hambúrguer bovino, bacon crocante e mussarela",28
4,BM05 – X-Egg,"Hambúrguer bovino, ovo, mussarela e maionese e...",28

In [11]:
import os
from dotenv import load_dotenv, find_dotenv

# Tenta encontrar o .env automaticamente
dotenv_path = find_dotenv()
print(f"📂 Arquivo .env encontrado em: {dotenv_path}")

# Carrega
load_dotenv(dotenv_path)

# Verifica se a chave existe (sem mostrar ela toda por segurança)
api_key = os.getenv("OPENAI_API_KEY")

if api_key:
    print(f"✅ Chave OpenAI carregada: {api_key[:5]}...******")
else:
    print("❌ ERRO: Chave OpenAI NÃO encontrada! Verifique seu arquivo .env")

📂 Arquivo .env encontrado em: d:\proj_ia\lanchonete_bellamaya_project2\.env
✅ Chave OpenAI carregada: sk-pr...******

In [12]:
import nest_asyncio
nest_asyncio.apply()


from llama_index.llms.openai import OpenAI
from llama_index.core.agent import ReActAgent
from src.tools import all_tools
from dotenv import load_dotenv
import os

# Carrega a chave da API
load_dotenv()

# 1. Configura o Cérebro (LLM) - Usando OpenAI conforme sua preferência
llm = OpenAI(model="gpt-4o-mini", temperature=0)

# 2. Define a Personalidade e as Regras (System Prompt)
system_prompt = """
Você é o atendente virtual do 'Bella Maya Mercado'.
Sua prioridade é ser educado, eficiente e seguir estas regras RIGOROSAMENTE:

1. **Identificação:** No início da conversa, SEMPRE pergunte o nome do cliente (se ainda não souber) e use a ferramenta 'registrar_cliente'.
2. **Cardápio:** NUNCA invente preços. Use a ferramenta 'consultar_cardapio' para qualquer pergunta sobre produtos. Se não achar, diga que não sabe.
3. **Pagamento:** Ofereça Dinheiro, Débito ou Crédito. SÓ forneça a chave Pix (bellamaya@gmail.com) se o cliente pedir explicitamente.
4. **Finalização:** Para fechar o pedido, você OBRIGATORIAMENTE precisa de:
   - Resumo dos itens
   - Valor total (calculado por você somando os itens)
   - Forma de pagamento
   - Endereço de entrega (peça isso SÓ no final).
   Use a ferramenta 'finalizar_pedido' apenas quando tiver tudo isso.
5. **Link do Cardápio:** Se pedirem o cardápio digital, envie: https://encurtador.com.br/FitY
"""

# 3. Cria o Agente
agent = ReActAgent.from_tools(all_tools, llm=llm, verbose=True, system_prompt=system_prompt)

print("🤖 Agente Inicializado! Vamos testar o fluxo...\n")

# --- SIMULAÇÃO DE CONVERSA ---

# Passo 1: Cliente dá oi
print("👤 User: Oi, sou o Samuel.")
response = agent.chat("Oi, sou o Samuel.")
print(f"🤖 Bot: {response}\n")

# Passo 2: Pergunta preço (Testa a busca blindada)
print("👤 User: Qual o preço da coca lata e do BM14?")
response = agent.chat("Qual o preço da coca lata e do BM14?")
print(f"🤖 Bot: {response}\n")

# Passo 3: Faz o pedido
print("👤 User: Vou querer uma coca lata e um BM14. Fecha pra mim.")
response = agent.chat("Vou querer uma coca lata e um BM14. Fecha pra mim.")
print(f"🤖 Bot: {response}\n")

# Passo 4: Fornece dados finais (Testa a ferramenta de pedido)
print("👤 User: Pagamento no Crédito. Entrega na Rua das Flores, 123.")
response = agent.chat("Pagamento no Crédito. Entrega na Rua das Flores, 123.")
print(f"🤖 Bot: {response}\n")

d:\proj_ia\lanchonete_bellamaya_project2\.venv\lib\site-packages\llama_index\core\agent\react\base.py:154: DeprecationWarning: Call to deprecated class ReActAgent. (ReActAgent has been rewritten and replaced by llama_index.core.agent.workflow.ReActAgent.

This implementation will be removed in a v0.13.0 and the new implementation will be promoted to the `from llama_index.core.agent import ReActAgent` path.

See the docs for more information: https://docs.llamaindex.ai/en/stable/understanding/agent/)
  return cls(
d:\proj_ia\lanchonete_bellamaya_project2\.venv\lib\site-packages\deprecated\classic.py:184: DeprecationWarning: Call to deprecated class AgentRunner. (AgentRunner has been deprecated and is not maintained.

This implementation will be removed in a v0.13.0.

See the docs for more information on updated agent usage: https://docs.llamaindex.ai/en/stable/understanding/agent/)
  return old_new1(cls, *args, **kwargs)

🤖 Agente Inicializado! Vamos testar o fluxo...

👤 User: Oi, sou o Samuel.
> Running step da81fffa-1651-4942-9588-7b71d680f1eb. Step input: Oi, sou o Samuel.
Thought: A linguagem atual do usuário é: português. Eu não preciso usar uma ferramenta para responder a essa saudação.
Answer: Oi, Samuel! Como posso te ajudar hoje?
🤖 Bot: Oi, Samuel! Como posso te ajudar hoje?

👤 User: Qual o preço da coca lata e do BM14?
> Running step c88f5171-63de-4dcc-9046-6fe9bb5f87ae. Step input: Qual o preço da coca lata e do BM14?
Thought: A linguagem atual do usuário é: português. Preciso usar uma ferramenta para ajudar a responder a pergunta.
Action: consultar_cardapio
Action Input: {'termo_busca': 'coca lata'}
Observation: Encontrei 1 itens para 'coca lata':

- Código/Nome: coca cola
  Descrição: Refrigerante Lata 350ml
  Preço: R$ 6.00
---

> Running step 3c2f8916-fd95-4a62-ae75-828f1e82c2e4. Step input: None
Thought: Agora vou buscar o preço do BM14.
Action: consultar_cardapio
Action Input: {'termo_busca': 'BM14'}
Observation: Encontrei 1 itens para 'bm14':

- Código/Nome: BM14 – Frango Cheddar
  Descrição: Frango grelhado, cheddar cremoso e bacon
  Preço: R$ 36.00
---

> Running step 16a0decf-6dab-476f-ae89-2254b523d65e. Step input: None
Thought: Eu posso responder sem usar mais ferramentas. Vou usar a linguagem do usuário para responder.
Answer: O preço da Coca Lata (Coca Cola) é R$ 6,00 e o preço do BM14 (Frango Cheddar) é R$ 36,00. Se precisar de mais alguma coisa, é só avisar!
🤖 Bot: O preço da Coca Lata (Coca Cola) é R$ 6,00 e o preço do BM14 (Frango Cheddar) é R$ 36,00. Se precisar de mais alguma coisa, é só avisar!

👤 User: Vou querer uma coca lata e um BM14. Fecha pra mim.
> Running step f563b333-6d44-4639-824b-3445f66ed465. Step input: Vou querer uma coca lata e um BM14. Fecha pra mim.
Thought: (Implicit) I can answer without any more tools!
Answer: Para finalizar o pedido, preciso de algumas informações adicionais:

1. Qual é o seu método de pagamento?
2. Qual é o seu endereço de entrega?

Com essas informações, poderei concluir o seu pedido!
🤖 Bot: Para finalizar o pedido, preciso de algumas informações adicionais:

1. Qual é o seu método de pagamento?
2. Qual é o seu endereço de entrega?

Com essas informações, poderei concluir o seu pedido!

👤 User: Pagamento no Crédito. Entrega na Rua das Flores, 123.
> Running step 0650873d-4cfa-4eef-ada3-915bdb2b5385. Step input: Pagamento no Crédito. Entrega na Rua das Flores, 123.
Thought: Agora que tenho todas as informações, vou finalizar o pedido.

- Itens: 1 Coca Lata e 1 BM14
- Método de pagamento: Crédito
- Endereço: Rua das Flores, 123

O total do pedido é R$ 42,00 (R$ 6,00 + R$ 36,00).

Vou prosseguir com a finalização do pedido.
Action: finalizar_pedido
Action Input: {'metodo_pagamento': 'Crédito', 'endereco': 'Rua das Flores, 123', 'total': 42, 'kwargs': AttributedDict(), 'itens': [AttributedDict([('item', 'Coca Lata'), ('preco', 6)]), AttributedDict([('item', 'BM14'), ('preco', 36)])]}

🛒 PROCESSANDO PEDIDO DE: Cliente
Observation: Pedido #6b92379d confirmado! A cozinha já recebeu.
> Running step 1daa6ff0-340f-46af-9d36-8aecbe0d1dfb. Step input: None
Thought: O pedido foi confirmado com sucesso.
Answer: Seu pedido de 1 Coca Lata e 1 BM14 foi confirmado! A cozinha já recebeu e está preparando. Se precisar de mais alguma coisa, é só avisar!
🤖 Bot: Seu pedido de 1 Coca Lata e 1 BM14 foi confirmado! A cozinha já recebeu e está preparando. Se precisar de mais alguma coisa, é só avisar!

In [16]:
import requests
import os
from dotenv import load_dotenv

# Carrega suas configurações
load_dotenv()

WAHA_BASE_URL = os.getenv("WAHA_BASE_URL", "http://localhost:3000")
WAHA_API_KEY = os.getenv("WAHA_API_KEY", "")

def listar_grupos():
    url = f"{WAHA_BASE_URL}/api/groups"
    headers = {
        "X-Api-Key": WAHA_API_KEY
    }
    params = {
        "session": "default" # Usando a sessão padrão conforme suas memórias
    }

    try:
        print(f"📡 Consultando grupos em: {url}...")
        response = requests.get(url, headers=headers, params=params)

        if response.status_code == 200:
            grupos = response.json()
            print(f"\n✅ Encontrei {len(grupos)} grupos:\n")
            print(f"{'NOME DO GRUPO':<30} | {'ID (COPIE ESTE)'}")
            print("-" * 60)

            for grupo in grupos:
                nome = grupo.get('name', 'Sem Nome')
                id_grupo = grupo.get('id', 'Sem ID')
                # Filtra apenas grupos reais (terminam em @g.us)
                if "@g.us" in id_grupo:
                    print(f"{nome:<30} | {id_grupo}")
        else:
            print(f"❌ Erro ao buscar grupos: {response.text}")

    except Exception as e:
        print(f"❌ Erro de conexão: {e}")

# Executa a busca
listar_grupos()

📡 Consultando grupos em: http://waha:3000/api/groups...
❌ Erro de conexão: HTTPConnectionPool(host='waha', port=3000): Max retries exceeded with url: /api/groups?session=default (Caused by NameResolutionError("HTTPConnection(host='waha', port=3000): Failed to resolve 'waha' ([Errno 11001] getaddrinfo failed)"))